### ISSUE TITLE
重构配置加载

### ISSUE THREAD

**Issue by trim21** [bangumi/server-private#48]
需求：

加载配置文件和环境变量。

环境变量可以覆盖对应的配置项。

如：

```yaml
db:
  mysql:
    host: '127.0.0.1'
```

可以对应环境变量 `db.mysql.host` 或者 `DB_MYSQL_HOST`, 取决于哪个实现起来简单。
